#!/usr/bin/perl

use HTTP::Request::Common qw(GET POST);
use LWP::UserAgent;
use LWP::Simple;

use strict;
use warnings;

my $hsh = '';

sub updateHsh () {
	my $ua = LWP::UserAgent->new();
	my $req = GET 'http://z-music.org/theme/new/js/lang',
			'Accept' => '*/*',
			'Accept-Language' => 'ru,ru-ru;q=0.8,en-us;q=0.5,en;q=0.3',
			'Cache-Control' => 'no-cache',
			'Connection' => 'keep-alive',
			'Content-Type' => 'application/x-www-form-urlencoded; charset=UTF-8',
			'Cookie' => 'lang=ru; volume=80; session=039481ff229f9c361ceb296a86762c7e; PHPSESSID=kadqin94p0o9jboai3evb20j50; _ym_visorc=w',
		 	'Pragma' => 'no-cache',
			'Referer' => 'http://z-music.org/',
			'User-Agent' => 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0',
			'X-Requested-With' => 'XMLHttpRequest';
	my $res = $ua->request($req);
	my $content = $res->content;
	if ($content =~ /var hsh="([^"]+)"/) {
		$hsh = $1;
	} else {
		die "Не удалось получить hsh из lang\n";
	}
}

sub getList ($$) {
	my @r;
	my $page = 1;
	while (1) {
		my $added = 0;
		print "getting page $page\n";
		my $html = get("$_[0]&page=$page");
		while ($html =~ /\G.*?<li class="track">(.*?)<\/li>/g) {
			my $content = $1;
			$content =~ /data-aid="([^"]+)"/;
			my $id = $1;
			$content =~ /<b class="artist">(.*?)<\/b>/;
			my $artist = $1;
			$content =~ /<span class="name">(.*?)<\/span>/;
			my $title = $1;
	
			push @r, [$id, $artist, $title];
			$added ++;
		}
		goto norec if !$added || !$_[1];
		$page ++;
	}
norec:

	return \@r;
}

sub getSearchList ($) {
	return getList ("http://z-music.org/search/?q=$_[0]", 1);
}

sub getArtistList ($) {
	return getList ("http://z-music.org/artist/$_[0]/?", 0);
}

sub getAlbumList ($$) {
	return getList ("http://z-music.org/artist/$_[0]/$_[1]/?", 0);
}

sub startPlay ($) {
	updateHsh ();
	my $ua = LWP::UserAgent->new();
	my $req = POST 'http://z-music.org/service/',
			'Accept' => '*/*',
			'Accept-Language' => 'ru,ru-ru;q=0.8,en-us;q=0.5,en;q=0.3',
			'Cache-Control' => 'no-cache',
			'Connection' => 'keep-alive',
			'Content-Type' => 'application/x-www-form-urlencoded; charset=UTF-8',
			'Cookie' => 'lang=ru; volume=80; session=039481ff229f9c361ceb296a86762c7e; PHPSESSID=kadqin94p0o9jboai3evb20j50; _ym_visorc=w',
		 	'Pragma' => 'no-cache',
			'Referer' => 'http://z-music.org/',
			'User-Agent' => 'Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0',
			'X-Requested-With' => 'XMLHttpRequest',
			Content => [
				artist => $_->[1],
				title => $_->[2],
				action => 'startplay'
			];
	my $res = $ua->request($req);
	my $s = $res->as_string;
	my $content = $res->content;
}

sub download ($) {
	my $r = $_[0]->();
	my $i = 0;
	foreach (@$r) {
		startPlay ($_);
		my $id = sprintf "%04i", $i;
		`wget -cO '$id $_->[1] - $_->[2].mp3' 'http://149.255.38.167/t/$_->[0]_$hsh/'`;
		$i++;
	}
}

sub play ($) {
	my $r = $_[0]->();
	foreach (@$r) {
		startPlay ($_);
		print "==== $_->[1] - $_->[2]\n";
		`mplayer -cache 512 -cache-min 50 'http://149.255.38.167/t/$_->[0]_$hsh/' 2>/dev/null`;
	}
}

my $getter;
if (@ARGV < 3) {
	die "Недостаточно аргументов"
}

if ($ARGV[1] eq 'search') {
	$getter = sub () { return getSearchList ($ARGV[2]) };
} elsif ($ARGV[1] eq 'artist') {
	$getter = sub () { return getArtistList ($ARGV[2]) };
} elsif ($ARGV[1] eq 'album') {
	if (@ARGV < 4) {
		die "Не указан альбом"
	}
	$getter = sub () { return getAlbumList ($ARGV[2], $ARGV[3]) };
} else {
	die "Неизвестный тип поиска '$ARGV[2]'"
}

if ($ARGV[0] eq 'play') {
	play ($getter);
} elsif ($ARGV[0] eq 'download') {
	download ($getter);
} else {
	die "Неизвестная команда: $ARGV[0]\n";
}
